fix build.rs
build.rs was causing the a crash during the installation with cargo : 

error[E0432]: unresolved import std::fs::exists
 --> imessage-database/build.rs:3:16
  |
3 |     fs::{copy, exists},
  |                ^^^^^^ no exists i